In [1]:
import torch 
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                             [.4, .5, .6],
                             [.7, .8, .9]])

In [3]:
x = torch.rand_like(target) # 0 ~ 1 범위에서 랜덤값으로 target 과 같은 shape의 텐서를 생성
x.requires_grad = True      # x 를 미분 가능한 텐서로 설정하여. backward() 호출 시 x에 대한 기울기 자동 계산 

x

tensor([[0.2915, 0.6547, 0.0097],
        [0.0255, 0.4657, 0.1507],
        [0.0211, 0.1772, 0.6772]], requires_grad=True)

In [4]:
loss = F.mse_loss(x,target)     # x와 target간의 평균제고옵차(MSE) 계산 (X는 예측값, target은 정답값으로 가정)
loss

tensor(0.1744, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5                                # 손실함수 종료 기준값
learning_rate = 1.                              # 가중치 업데이트 사용할 학습률
iter_cnt = 0                                    # 반복 횟수 카운터 초기화

while loss > threshold:                         # 손실이 임계값보다 클 동안 반복
    iter_cnt += 1                               # 반복 횟수 증가
    
    loss.backward()                             # loss에 대한 역전파 수행(loss)
    
    x = x - learning_rate * x.grad              # gradient descent 방식으로 x를 업데이트
    
    x.detach_()                                 # 기존 계산그래프에서 x 분리
    x.requires_grad_(True)                      # 다음 반복을 위해 gradient 추적 다시 활성화
    
    loss = F.mse_loss(x, target)                # 업데이트 x로 새로운 손실 계산
    
    print(f"{iter_cnt}번째 : Loss : {loss}")    # 현재 반복의 손실 값 출력
    print(x)
    

1번째 : Loss : 0.10548523813486099
tensor([[0.2490, 0.5536, 0.0742],
        [0.1087, 0.4734, 0.2505],
        [0.1720, 0.3156, 0.7267]], requires_grad=True)
2번째 : Loss : 0.06381206214427948
tensor([[0.2159, 0.4750, 0.1244],
        [0.1734, 0.4793, 0.3282],
        [0.2893, 0.4233, 0.7652]], requires_grad=True)
3번째 : Loss : 0.03860235586762428
tensor([[0.1901, 0.4139, 0.1634],
        [0.2238, 0.4839, 0.3886],
        [0.3806, 0.5070, 0.7952]], requires_grad=True)
4번째 : Loss : 0.023352041840553284
tensor([[0.1701, 0.3664, 0.1938],
        [0.2629, 0.4875, 0.4356],
        [0.4516, 0.5721, 0.8185]], requires_grad=True)
5번째 : Loss : 0.014126542955636978
tensor([[0.1545, 0.3294, 0.2174],
        [0.2934, 0.4902, 0.4721],
        [0.5068, 0.6227, 0.8366]], requires_grad=True)
6번째 : Loss : 0.008545687422156334
tensor([[0.1424, 0.3007, 0.2357],
        [0.3171, 0.4924, 0.5005],
        [0.5497, 0.6621, 0.8507]], requires_grad=True)
7번째 : Loss : 0.005169613752514124
tensor([[0.1330, 0.2783, 0.