In [17]:
import torch 
import torch.nn.functional as F

In [18]:
target = torch.FloatTensor([[.1, .2, .3],
                             [.4, .5, .6],
                             [.7, .8, .9]])

In [19]:
x = torch.rand_like(target) # 0 ~ 1 범위에서 랜덤값으로 target 과 같은 shape의 텐서를 생성
x.requires_grad = True      # x 를 미분 가능한 텐서로 설정하여. backward() 호출 시 x에 대한 기울기 자동 계산 

x

tensor([[0.1164, 0.0830, 0.1077],
        [0.7947, 0.4907, 0.5815],
        [0.8982, 0.5006, 0.7905]], requires_grad=True)

In [20]:
loss = F.mse_loss(x,target)     # x와 target간의 평균제고옵차(MSE) 계산 (X는 예측값, target은 정답값으로 가정)
loss

tensor(0.0387, grad_fn=<MseLossBackward0>)

In [ ]:
threshold = 1e-5                                # 손실함수 종료 기준값
learning_rate = 1.                              # 가중치 업데이트 사용할 학습률
iter_cnt = 0                                    # 반복 횟수 카운터 초기화

while loss > threshold:                         # 손실이 임계값보다 클 동안 반복
    iter_cnt += 1                               # 반복 횟수 증가
    
    loss.backward()                             # loss에 대한 역전파 수행(loss)
    
    x = x - learning_rate * x.grad              # gradient descent 방식으로 x를 업데이트
    
    x.detach_()                                 # 기존 계산그래프에서 x 분리
    x.requires_grad_(True)                      # 다음 반복을 위해 gradient 추적 다시 활성화
    
    loss = F.mse_loss(x, target)                # 업데이트 x로 새로운 손실 계산
    
    print(f"{iter_cnt}번째 : Loss : {loss}")    # 현재 반복의 손실 값 출력
    print(x)
    

1번째 : Loss : 0.023396246135234833
tensor([[0.1128, 0.1090, 0.1504],
        [0.7070, 0.4928, 0.5856],
        [0.8542, 0.5671, 0.8148]], requires_grad=True)
2번째 : Loss : 0.014153284952044487
tensor([[0.1099, 0.1292, 0.1837],
        [0.6387, 0.4944, 0.5888],
        [0.8199, 0.6189, 0.8337]], requires_grad=True)
3번째 : Loss : 0.008561864495277405
tensor([[0.1077, 0.1450, 0.2095],
        [0.5857, 0.4956, 0.5913],
        [0.7933, 0.6591, 0.8485]], requires_grad=True)
4번째 : Loss : 0.005179400090128183
tensor([[0.1060, 0.1572, 0.2296],
        [0.5444, 0.4966, 0.5932],
        [0.7725, 0.6904, 0.8599]], requires_grad=True)
5번째 : Loss : 0.0031332168728113174
tensor([[0.1047, 0.1667, 0.2453],
        [0.5123, 0.4974, 0.5947],
        [0.7564, 0.7148, 0.8688]], requires_grad=True)
6번째 : Loss : 0.0018954032566398382
tensor([[0.1036, 0.1741, 0.2574],
        [0.4874, 0.4979, 0.5959],
        [0.7439, 0.7337, 0.8758]], requires_grad=True)
7번째 : Loss : 0.0011466015130281448
tensor([[0.1028, 0.17