In [1]:
import torch

In [2]:
# 역전파를 위해서 x에 대한 gradient 계산 활성
x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)


In [3]:
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [4]:
# 연산트리 자동 생성
x1 = x + 2              # 모든 원소에 + 2
x2 = x - 2              # 모든 원소에 - 2
x3 = x1 * x2            # (x+2)와 (x-2) 텐서를 원소별로 곱함
y = x3.sum()            # 모든 원소를 더해 스칼라값으로 변환

print(x1)
print(x2)
print(x3)
print(y)


tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [ ]:
# 자동 미분을 통한 역전파
y.backward() 
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [6]:
x3.detach_().numpy()    # inplace 계산그래프 분리

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

In [7]:
print(x3.numpy())

[[-3.  0.]
 [ 5. 12.]]
